#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <stdlib.h>
#include <ctype.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <termio.h>
#include <termios.h>

/* This file was generated by QuickBasic to C translator */
/* qb2c  ver.1.0 Jan-1996                                */

#define LMAX 1024

/* Function declarations */
extern int    LEN(char *);
extern char  *INKEY_S(void);

/* Shared variables and arrays declarations */
static struct termio term_orig;
static int  kbdflgs;
static char   w__S[16][LMAX];
static int    j__S = 0;
static double x__d[16];
static int    i__x = 0;
static char  *keys__S[]  = {"Spacebar",
"F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12",
"Insert", "Home", "PageUp", 
"Delete", "End", "PageDown",
               "Arrow Up",
"Arrow Left", "Arrow Down", "Arrow Right" };
static int    n__keys = 23;

/* Open files pointers */
FILE *fp_1, *fp_2;

main()
{
 static int i, j, k=0, l=0;
 static char a_S[LMAX], tbl_S[LMAX];

 strcpy(tbl_S,getenv("HOME"));
 strcat(tbl_S,"/.kbcalib");
 if((fp_1 = fopen("calib.log", "w")) == NULL)
 {
  fprintf(stderr,"calib: cant open file %s\n","calib.log"); exit(0);
 }
 if((fp_2 = fopen(tbl_S, "w")) == NULL)
 {
  fprintf(stderr,"calib: cant create file %s\n",tbl_S); exit(0);
 }
 for(j = 0; j < n__keys; j++)
 {
  if(j == n__keys) printf("Numerical keyboard:\n");
  printf("Press %s:\n",keys__S[j]);
  strcpy(a_S,INKEY_S());
  if (j > 0) fprintf(fp_2,"%s\n",a_S);
  fprintf(fp_1,"%-12s",keys__S[j]);
  for(i = 0; i <= LEN(a_S) - 1; i++)
  {
   fprintf(fp_1,"%d ", a_S[i]);
  }
  fprintf(fp_1,"\n");
  if(strcmp(a_S, "q") == 0) { goto Lab_999; }
  for (k=1; k<=32000; k=k+1) l=l+.5*2;  /* a small pause */
  printf("\b  OK!\n");
 } 
Lab_999:
 fclose(fp_1);
 fclose(fp_2);
 exit(0);
} /* End of MAIN */

/* Translates of used QB's intrinsic functions: */

extern int LEN(char *a_S)
{
 if (++i__x == 16) i__x = 0;
 x__d[i__x] = strlen(a_S);
 return x__d[i__x];
}

extern char  *INKEY_S(void)
{
 static int i;

 if (++j__S == 16) j__S=0;
 input_mode();
 while((i=read(0,w__S[j__S],5)) < 1);
 w__S[j__S][i]=0;
 system_mode();
 if (w__S[j__S][0] == 3) exit(0);
 return w__S[j__S];
}

int system_mode(void)
{
    if (ioctl(0, TCSETA, &term_orig) == -1) {
        return (0);
    }
    fcntl(0, F_SETFL, kbdflgs);
}

int input_mode(void)
{
    static struct termio term;
    static int flags;

    if (ioctl(0, TCGETA, &term) == -1) {
        return (-1);
    }
    (void) ioctl(0, TCGETA, &term_orig);
    term.c_iflag = 0;
    term.c_oflag = 0;
    term.c_lflag = 0;
    term.c_cc[VMIN] = 1;
    term.c_cc[VTIME] = 0;
    if (ioctl(0, TCSETA, &term) == -1) {
        return (-1);
    }
    kbdflgs = fcntl(0, F_GETFL, 0);
    flags = fcntl(0, F_GETFL);
    flags &= ~O_NDELAY;
    fcntl(0, F_SETFL, flags);
    return (0);
}
