#!/bin/bash

#Copyright (C) 2006 Abhishek Choudhary
#This file is part of the Hindawi Indic Programming System.
#
#The Hindawi Indic Programming System is free software; 
#you can redistribute it and/or modify it under the terms of the 
#GNU General Public License as published by the 
#Free Software Foundation; either version 2 of the License, or 
#(at your option) any later version.
#
#The Hindawi Indic Programming System is distributed in the hope 
#that it will be useful, but WITHOUT ANY WARRANTY; without 
#even the implied warranty of MERCHANTABILITY or FITNESS FOR 
#A PARTICULAR PURPOSE. See the GNU General Public License for 
#more details.
#
#You should have received a copy of the GNU General Public
#License along with this file; see the file COPYING. If
#not, write to the Free Software Foundation,
#51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
#Modifications: (Please maintain in reverse chronological order)
#
#  dd-mmm-yyyy, Nature of change,
#                 Changed by <alias>,
#                 email@server.tld
#
#  31-Jul-2006, Created script, Ver. 0.2.0,
#                 Abhishek Choudhary <hi_pedler>,
#                 choudhary@indicybers.net

#Script for Hindawi Indic Programming System Ver. 0.2.0 - install Hindawi suite

cd APCISR
make all
make install
make clean_all
cd ..
cd HindawiUI
make all
make install
make clean_all
cd ..
cd HindawiLauncher
make all
make install
make clean_all
cd ..
cd Romenagri
make all
make install
make clean_all
cd ..
cd RomenagriUI
make all
make install
make clean_all
cd ..
cd RomenagriMail
make all
make install
make clean_all
cd ..

cd Hindawi
cd guru
make all
make install
make clean_all
cd ..
cd hindrv
make all
make install
make clean_all
cd ..
cd kritrima
make all
make install
make clean_all
cd ..
cd praatha
make all
make install
make clean_all
cd ..
cd shabda
make all
make install
make clean_all
cd ..
cd shraeni
make all
make install
make clean_all
cd ..
cd wyaaka
make all
make install
make clean_all
cd ..
cd yantra
make all
make install
make clean_all
cd ..

cd others
cd fasm
make all
make install
make clean_all
cd ..
cd qb2c
make all
make install
make clean_all
cd ..

cd ~
echo -e "\n\nInstallation complete\n"