#!/bin/bash

#Copyright (C) 2006 Abhishek Choudhary
#This file is part of the Hindawi Indic Programming System.
#
#The Hindawi Indic Programming System is free software; 
#you can redistribute it and/or modify it under the terms of the 
#GNU General Public License as published by the 
#Free Software Foundation; either version 2 of the License, or 
#(at your option) any later version.
#
#The Hindawi Indic Programming System is distributed in the hope 
#that it will be useful, but WITHOUT ANY WARRANTY; without 
#even the implied warranty of MERCHANTABILITY or FITNESS FOR 
#A PARTICULAR PURPOSE. See the GNU General Public License for 
#more details.
#
#You should have received a copy of the GNU General Public
#License along with this file; see the file COPYING. If
#not, write to the Free Software Foundation,
#51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
#Modifications: (Please maintain in reverse chronological order)
#
#  dd-mmm-yyyy, Nature of change,
#                 Changed by <alias>,
#                 email@server.tld
#
#  31-Jul-2006, Created script, Ver. 0.2.0,
#                 Abhishek Choudhary <hi_pedler>,
#                 choudhary@indicybers.net

#Script for Hindawi Indic Programming System Ver. 0.2.0 - uninstall Hindawi suite

cd APCISR
make uninstall
cd ..
cd HindawiUI
make uninstall
cd ..
cd HindawiLauncher
make uninstall
cd ..
cd Romenagri
make uninstall
cd ..
cd RomenagriUI
make uninstall
cd ..
cd RomenagriMail
make uninstall
cd ..

cd Hindawi
cd guru
make uninstall
cd ..
cd hindrv
make uninstall
cd ..
cd kritrima
make uninstall
cd ..
cd praatha
make uninstall
cd ..
cd shabda
make uninstall
cd ..
cd shraeni
make uninstall
cd ..
cd wyaaka
make uninstall
cd ..
cd yantra
make uninstall
cd ..

cd others
cd fasm
make uninstall
cd ..
cd qb2c
make uninstall
cd ..

cd ~
echo -e "\n\nUninstallation complete\n"