#!/bin/bash

#Copyright (C) 2006 Abhishek Choudhary
#This file is part of the Hindawi Indic Programming System.
#
#The Hindawi Indic Programming System is free software; 
#you can redistribute it and/or modify it under the terms of the 
#GNU General Public License as published by the 
#Free Software Foundation; either version 2 of the License, or 
#(at your option) any later version.
#
#The Hindawi Indic Programming System is distributed in the hope 
#that it will be useful, but WITHOUT ANY WARRANTY; without 
#even the implied warranty of MERCHANTABILITY or FITNESS FOR 
#A PARTICULAR PURPOSE. See the GNU General Public License for 
#more details.
#
#You should have received a copy of the GNU General Public
#License along with this file; see the file COPYING. If
#not, write to the Free Software Foundation,
#51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
#Modifications: (Please maintain in reverse chronological order)
#
#  dd-mmm-yyyy, Nature of change,
#                 Changed by <alias>,
#                 email@server.tld
#
#  31-Jul-2006, Created script, Ver. 0.2.0,
#                 Abhishek Choudhary <hi_pedler>,
#                 choudhary@indicybers.net

#Script for Hindawi Indic Programming System Ver. 0.2.0 - Shaili praathamika

echo संकलन के परिणाम
echo ============
rm -f *.b2c
cat $1 | tr "\t" "    " | acii2uni | iconv -f UTF-16 -t UTF-8 | h2b > tempfil01234.tmphin.bas
#bcpp -C tempfil01234.tmphin.bas 2>> tempfil0123.tmphin
#mv tempfil01234.tmphin.bcp tempfil0123.tmphin.bas
#qb2c -b -C tempfil0123.tmphin 2>> tempfil0123.tmphin
mv tempfil01234.tmphin.bas tempfil0123.tmphin.bas
qb2c -C tempfil0123.tmphin 2>> tempfil0123.tmphin
gcc -ansi tempfil0123.tmphin.c -ohin.exe -lqbX11 -lX11 -lm -L/usr/X11R6/lib 2>> tempfil0123.tmphin
cat tempfil0123.tmphin
rm tempfil0123.tmphin
