#Modified by Abhishek Choudhary for distribution with Hindawi
#The license terms remain same as those for FASM

EXECDIR=/usr/bin

all:

clean_all: clean

clean:

install:
	install fasm $(INSTROOT)$(EXECDIR)/fasm

uninstall:
	rm $(INSTROOT)$(EXECDIR)/fasm
